apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ghfkq9sq6-python
  janus-idp.io/tekton: ghfkq9sq6-python
  backstage.io/kubernetes-id: ghfkq9sq6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ghfkq9sq6-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
